"""Tests for Spike extension generator."""

from __future__ import annotations

from pathlib import Path

from rvxv.core.spec_parser import load_spec
from rvxv.generators.spike.spike_gen import SpikeGenerator


class TestSpikeGenerator:
    def test_generate_int8_dot(self, tmp_path):
        specs = load_spec(Path("examples/int8_dot_product.yaml"))
        gen = SpikeGenerator()
        files = gen.generate(specs, tmp_path)

        assert len(files) > 0

        # Check rvxv_encoding.h exists and has MATCH/MASK
        encoding_h = tmp_path / "spike" / "rvxv_encoding.h"
        assert encoding_h.exists()
        content = encoding_h.read_text()
        assert "MATCH_VDOT4_I8I8_ACC32" in content
        assert "MASK_VDOT4_I8I8_ACC32" in content

    def test_generate_creates_insn_files(self, tmp_path):
        specs = load_spec(Path("examples/int8_dot_product.yaml"))
        gen = SpikeGenerator()
        gen.generate(specs, tmp_path)

        insn_file = tmp_path / "spike" / "insns" / "vdot4_i8i8_acc32.h"
        assert insn_file.exists()
        content = insn_file.read_text()
        assert "Auto-generated by RVXV" in content

    def test_generate_all_examples(self, tmp_path):
        for path in Path("examples").glob("*.yaml"):
            specs = load_spec(path)
            gen = SpikeGenerator()
            output = tmp_path / path.stem
            files = gen.generate(specs, output)
            assert len(files) > 0

    def test_generate_preset(self, tmp_path):
        from rvxv.presets.registry import load_preset
        specs = load_preset("common_ai_ops")
        gen = SpikeGenerator()
        files = gen.generate(specs, tmp_path)
        assert len(files) > 0
