"""Human-readable instruction specification document generator."""

from __future__ import annotations

from pathlib import Path

from rvxv.core.instruction_ir import InstructionSpec
from rvxv.core.type_system import get_type_info
from rvxv.generators.base import Generator


class DocGenerator(Generator):
    """Generate human-readable instruction documentation."""

    def generate(self, specs: list[InstructionSpec], output_dir: Path) -> list[Path]:
        output_dir = output_dir / "docs"
        self._ensure_dir(output_dir)

        generated = []

        # Generate individual instruction docs
        for spec in specs:
            path = output_dir / f"{spec.name}.md"
            path.write_text(self._render_spec_doc(spec))
            generated.append(path)

        # Generate summary document
        summary_path = output_dir / "instruction_summary.md"
        summary_path.write_text(self._render_summary(specs))
        generated.append(summary_path)

        return generated

    def _render_spec_doc(self, spec: InstructionSpec) -> str:
        lines = [
            f"# {spec.name}",
            "",
            f"**{spec.description}**",
            "",
            "*Auto-generated by RVXV — RISC-V AI Extension Verification Platform*",
            "",
            "---",
            "",
            "## Encoding",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| Format | {spec.encoding.format} |",
            f"| Opcode | `0x{spec.encoding.opcode:02X}` |",
            f"| funct3 | `0x{spec.encoding.funct3:X}` |",
        ]

        if spec.encoding.funct7 is not None:
            lines.append(f"| funct7 | `0x{spec.encoding.funct7:02X}` |")
        if spec.encoding.funct6 is not None:
            lines.append(f"| funct6 | `0x{spec.encoding.funct6:02X}` |")
        if spec.encoding.funct2 is not None:
            lines.append(f"| funct2 | `0x{spec.encoding.funct2:X}` |")

        lines.extend([
            f"| MATCH | `0x{spec.encoding.match_value:08X}` |",
            f"| MASK | `0x{spec.encoding.mask_value:08X}` |",
            "",
            "### Binary Encoding",
            "",
            "```",
            self._render_encoding_diagram(spec),
            "```",
            "",
            "## Operands",
            "",
            "| Name | Type | Element | Groups | Register |",
            "|------|------|---------|--------|----------|",
        ])

        for name, op in spec.operands.items():
            info = get_type_info(op.element)
            lines.append(
                f"| {name} | {op.type} | {op.element.value} "
                f"({info.width_bits}b) | {op.groups} | {op.register_class} |"
            )

        lines.extend([
            "",
            "## Semantics",
            "",
            f"- **Operation**: {spec.semantics.operation.value}",
            f"- **Accumulate**: {'Yes' if spec.semantics.accumulate else 'No'}",
            f"- **Saturation**: {spec.semantics.saturation}",
            f"- **Rounding**: {spec.semantics.rounding}",
            "",
            "## Constraints",
            "",
            f"- **VL dependent**: {'Yes' if spec.constraints.vl_dependent else 'No'}",
            f"- **Mask agnostic**: {'Yes' if spec.constraints.mask_agnostic else 'No'}",
            f"- **Tail agnostic**: {'Yes' if spec.constraints.tail_agnostic else 'No'}",
        ])

        if spec.constraints.min_sew is not None:
            lines.append(f"- **Min SEW**: {spec.constraints.min_sew}")
        if spec.constraints.max_sew is not None:
            lines.append(f"- **Max SEW**: {spec.constraints.max_sew}")
        if spec.constraints.required_lmul is not None:
            lines.append(f"- **Required LMUL**: {spec.constraints.required_lmul}")

        lines.extend([
            "",
            "## Assembly Syntax",
            "",
            "```asm",
            "# Using .insn directive (for assemblers that don't know this instruction)",
        ])

        operand_names = list(spec.operands.keys())
        if spec.encoding.format in ("R-type", "vector"):
            has_dest = any(
                k.startswith("vd") or k.startswith("rd") for k in operand_names
            )
            rd = operand_names[-1] if has_dest else operand_names[0]
            sources = [k for k in operand_names if k != rd]
            rs1 = sources[0] if sources else "x0"
            rs2 = sources[1] if len(sources) > 1 else "x0"
            f7 = spec.encoding.funct7 if spec.encoding.funct7 is not None else 0
            lines.append(
                f".insn r 0x{spec.encoding.opcode:02x}, "
                f"0x{spec.encoding.funct3:x}, "
                f"0x{f7:02x}, {rd}, {rs1}, {rs2}"
            )

        lines.extend([
            "```",
            "",
        ])

        return "\n".join(lines)

    def _render_encoding_diagram(self, spec: InstructionSpec) -> str:
        """Render ASCII encoding diagram."""
        if spec.encoding.format == "R-type":
            f7 = spec.encoding.funct7 if spec.encoding.funct7 is not None else 0
            return (
                f"31       25 24   20 19   15 14  12 11    7 6     0\n"
                f"| funct7  |  rs2  |  rs1  |funct3|  rd   |opcode |\n"
                f"|{f7:07b} | xxxxx | xxxxx |"
                f" {spec.encoding.funct3:03b} | xxxxx |{spec.encoding.opcode:07b}|"
            )
        elif spec.encoding.format == "vector":
            f6 = spec.encoding.funct6 if spec.encoding.funct6 is not None else 0
            vm = "1" if spec.encoding.vm else "0"
            return (
                f"31     26 25 24   20 19   15 14  12 11    7 6     0\n"
                f"|funct6 |vm|  vs2  |  vs1  |funct3|  vd   |opcode |\n"
                f"|{f6:06b}| {vm}| xxxxx | xxxxx |"
                f" {spec.encoding.funct3:03b} | xxxxx |{spec.encoding.opcode:07b}|"
            )
        return f"[{spec.encoding.format} format diagram]"

    def _render_summary(self, specs: list[InstructionSpec]) -> str:
        lines = [
            "# Instruction Summary",
            "",
            f"*Auto-generated by RVXV — {len(specs)} instruction(s)*",
            "",
            "| Instruction | Description | Format | Operation | Element Types |",
            "|-------------|-------------|--------|-----------|---------------|",
        ]

        for spec in specs:
            elem_types = ", ".join(
                v.element.value for v in spec.operands.values()
            )
            lines.append(
                f"| `{spec.name}` | {spec.description} | "
                f"{spec.encoding.format} | {spec.semantics.operation.value} | {elem_types} |"
            )

        lines.append("")
        return "\n".join(lines)
